### ISSUE TITLE
A question about "running coupled problems"

### ISSUE THREAD

**Issue by GGY-IC** [jkfurtney/PFC3D_OpenFOAM#2]
What is the reason for this problem? It is because of the file "itasca-2016.06.09"“ itasca.py "Is there an error in the content of? I really hope to get a reply.

opfc@opfc-virtual-machine:~c/PFC3D_OpenFOAM/dropTest1$ python cfd_dropTest1.py
/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v3.0+                                 |
|   \\  /    A nd           | Web:      www.OpenFOAM.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
Build  : v3.0+-e941ee6c15e9
Exec   : demIcoFoam
Date   : Mar 11 2021
Time   : 17:41:39
Host   : "opfc-virtual-machine"
PID    : 4536
Case   : /home/opfcc/PFC3D_OpenFOAM/dropTest1
nProcs : 1
sigFpe : Enabling floating point exception trapping (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
creating demIcoFoam object

PISO: Operating solver in PISO mode

cleaning up socket
Traceback (most recent call last):
  File "cfd_dropTest1.py", line 33, in <module>
    print "send finished"
  File "/home/opfc/.localb/python2.7/site-packages/itasca/itasca.py", line 535, in __exit__
    self.close()
  File "/home/opfc/.localb/python2.7/site-packages/itasca/itasca.py", line 527, in close
    self.socket.shutdown(socket.SHUT_RDWR)
  File "/usrb/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 107] Transport endpoint is not connected
cleaning up demIcoFoam

cleaning up demBaseFoam

**Comment by goatwarren** [comment]
> 
Hello!
There is no problem before running 'python setup.py install --user' as follows:
~/src/PFC3D_OpenFOAM/pyDemFoam$ python setup.py install --user
building version 2016.06.09
running install
running build
running build_py
running build_ext
running install_lib
running install_egg_info
Removing /home/zhouyu/.local/lib/python2.7/site-packages/pyDemFoam-2016.06.09.egg-info
Writing /home/zhouyu/.local/lib/python2.7/site-packages/pyDemFoam-2016.06.09.egg-info

However, when running 'python -c "import pyDemFoam; print pyDemFoam.version"', it replies that：
Traceback (most recent call last):
File "", line 1, in
File "/home/zhouyu/.local/lib/python2.7/site-packages/pyDemFoam/init.py", line 3, in
from _pyDemFoam import pyDemIcoFoam, pyDemSimpleFoam
ImportError: /home/zhouyu/.local/lib/python2.7/site-packages/_pyDemFoam.so: undefined symbol: _ZN4Foam9UIPstream4readERi

Looking forward to your helping very much.

**Comment by jkfurtney** [comment]
Hello, Thank you for your interest in using PFC3D with OpenFOAM. Could you please contact pfcsupport@itascacg.com with your question. Thanks
