### ISSUE TITLE
There are errors after building pyDemFoam.

### ISSUE THREAD

**Issue by Python-Zhou** [jkfurtney/PFC3D_OpenFOAM#3]
**There is no problem before running 'python setup.py install --user' as follows:**
~/src/PFC3D_OpenFOAM/pyDemFoam$ python setup.py install --user
building version 2016.06.09
running install
running build
running build_py
running build_ext
running install_lib
running install_egg_info
Removing /home/zhouyu/.local/lib/python2.7/site-packages/pyDemFoam-2016.06.09.egg-info
Writing /home/zhouyu/.local/lib/python2.7/site-packages/pyDemFoam-2016.06.09.egg-info

**However, when running 'python -c "import pyDemFoam; print pyDemFoam.__version__"', it replies that：**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zhouyu/.local/lib/python2.7/site-packages/pyDemFoam/__init__.py", line 3, in <module>
    from _pyDemFoam import pyDemIcoFoam, pyDemSimpleFoam
ImportError: /home/zhouyu/.local/lib/python2.7/site-packages/_pyDemFoam.so: undefined symbol: _ZN4Foam9UIPstream4readERi

Looking forward to your helping very much.
Best regards
Yu

**Comment by goatwarren** [comment]
I have the same problem.

**Comment by jkfurtney** [comment]
Hello, Thank you for your interest in using PFC3D with OpenFOAM. Could you please contact pfcsupport@itascacg.com with your question. Thanks
