### ISSUE TITLE
A problem occured when I ran the code "pfc3d700_console call pfc_dropTest1.py"

### ISSUE THREAD

**Issue by Hansenn22** [jkfurtney/PFC3D_OpenFOAM#5]
Dear Furtney
I met a problem when I tested the code "pfc3d700_console call pfc_dropTest1.py". I listed the error report as below.
I don't how to handle it. So I turn to you. Hope to hear from you.
Best wishes.
Hansenn

Traceback (most recent call last):
  File "<string>", line 6, in <module>
AttributeError: module 'linecache' has no attribute '_ipython_cache'
pfc3d>python-reset-state on

**Comment by jkfurtney** [comment]
Hi Hansen, thanks for the message, can you send your inquiry to PFCsupport@itascacg.com please?

**Comment by Hansenn22** [comment]
Thanks for your suggestioin. I will write an email to the Itasca technical supportor.

**Comment by Hansenn22** [comment]
> Hi Hansen, thanks for the message, can you send your inquiry to [PFCsupport@itascacg.com](mailto:PFCsupport@itascacg.com) please?

Dear Furtney
I met a problem when I executed "cfd_ropTest1.py". The details are listed as follows. Can you give a guide to handle this problem? 
Regard,
Hansenn

--> FOAM FATAL ERROR: (openfoam-2112)
Cannot find file "points" in directory "polyMesh" in times "0" down to constant
    From virtual Foam::IOobject Foam::fileOperation::findInstance(const Foam::IOobject&, Foam::scalar, const Foam::word&) const
    in file global/fileOperations/fileOperation/fileOperation.C at line 1137.
FOAM exiting

**Comment by zx-0884** [comment]
I also encountered the same error. How did you solve it?
