### ISSUE TITLE
Can we couple the PFC3D 5.0 with OpenFOAM v2112?

### ISSUE THREAD

**Issue by rgwhfs** [jkfurtney/PFC3D_OpenFOAM#7]
Can we couple the PFC3D 5.0 with OpenFOAM v2112?

**Comment by goatwarren** [comment]
Hello, when I install pyDemFoam, it shows that 'undefined symbol' . How can I solve this problem

**Comment by goatwarren** [comment]
> Can we couple the PFC3D 5.0 with OpenFOAM v2112?
yes, but you should install the pyDemFoam successfully

**Comment by jkfurtney** [comment]
OK looks like this one is resolved.
