### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by goatwarren** [jkfurtney/PFC3D_OpenFOAM#8]
Hello, thank you very much for providing the OpenFOAM--PFC coupling package. I encountered a problem in the process of using it.
The error message is：  [Errno 111] Connection refused
looking forward to your reply！

**Comment by jkfurtney** [comment]
Thanks for your message and thanks for your interest in PFC3D. Could you email PFCsupport@itascacg.com with your PFC license serial number and more details of your problem?
