### ISSUE TITLE
PFC-CFD

### ISSUE THREAD

**Issue by Armin268** [jkfurtney/PFC3D_OpenFOAM#9]
Can we couple the PFC3D 7.0 with COMSOL v6.1?
I heard that we can use MATLAB in this case.
is there any code or example in this case?

**Comment by jkfurtney** [comment]
You should be able to connect PFC with any other software in the same way this repo demonstrates how to connect to OpenFOAM. Please contact pfcsupport@itascacg.com if you have questions about Itasca's PFC software.

**Comment by Armin268** [comment]
> 

Thank you so much for the answer.
Is there anyway to run your codes in Windows, not Ubuntu ?

**Comment by jkfurtney** [comment]
Please contact pfcsupport@itascacg.com

**Comment by zhujinzhuo** [comment]
> 我们能否将 PFC3D 7.0 与 COMSOL v6.1 结合使用？我听说在这种情况下可以使用 MATLAB。在这种情况下是否有任何代码或示例？

Hello.
Is there code for PFC-COMSOL coupling to exchange information with each other?
I would be most grateful.
